# Application
spring.application.name=stream-chat
server.port=8080

# Active Profile
spring.profiles.active=dev

# Logging
logging.level.root=INFO
logging.level.com.streamchat=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n